# Generated by Django 4.0.4 on 2022-04-16 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Company name')),
                ('quote', models.IntegerField(verbose_name='Quote traffic')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=120, verbose_name='First name')),
                ('last_name', models.CharField(max_length=240, verbose_name='Last name')),
                ('email', models.EmailField(max_length=120, verbose_name='Email')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.company', verbose_name='Company')),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Time')),
                ('resource', models.CharField(default='http://xxxx.xxx/xx.xx', max_length=240, verbose_name='Resource')),
                ('traffic', models.IntegerField(verbose_name='Transfer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user', verbose_name='User')),
            ],
        ),
    ]
