# Generated by Django 2.2 on 2019-04-10 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='quote',
            field=models.IntegerField(verbose_name='Quote traffic'),
        ),
    ]
