# Generated by Django 2.2 on 2019-04-10 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190410_0749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='resource',
            field=models.CharField(default='http://xxxx.xxx/xx.xx', max_length=240, verbose_name='Recource'),
        ),
    ]
