# Generated by Django 2.2 on 2019-04-15 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190410_0754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='resource',
            field=models.CharField(default='http://xxxx.xxx/xx.xx', max_length=240, verbose_name='Resource'),
        ),
    ]
